CC = g++
all: dumpArray makeArray sorter xd
	
	
dumpArray: dumpArray.cpp
	$(CC) dumpArray.cpp -o dumpArray
	
makeArray: makeArray.cpp
	$(CC) makeArray.cpp -o makeArray
	
sorter: sorter.cpp
	$(CC) sorter.cpp -o sorter
	
xd: xd.cpp
	$(CC) xd.cpp -o xd
	
clean:
	rm dumpArray makeArray sorter xd
