all:
	c++ -c  cc4.cpp Pack.cpp Monster.cpp Ogre.cpp Troll.cpp Human.cpp HalfElf.cpp Elf.cpp Orc.cpp Humanoid.cpp SkillRules.cpp handle4.cpp
	c++ cc4.o Monster.o Ogre.o Troll.o voc.o equip.o armor.o wpn.o dice.o gamespace.o Human.o HalfElf.o Elf.o Orc.o Humanoid.o SkillRules.o Pack.o handle4.o p4t.cpp -o run
	./run
