all:
	c++ -c cc3.cpp Pack.cpp Monster.cpp Ogre.cpp Troll.cpp Human.cpp HalfElf.cpp Elf.cpp Orc.cpp Humanoid.cpp SkillRules.cpp 
	c++ cc3.o Monster.o Ogre.o Troll.o voc.o equip.o armor.o wpn.o dice.o gamespace.o Human.o HalfElf.o Elf.o Orc.o Humanoid.o SkillRules.o Pack.o test2.cpp -o run
	./run