#!/bin/bash
#rm scrlab1.out
cp ../files/* .
c++ lab1.cpp -c &>compile_error.out
c++ lab1.o -o lab1.exe &> link_error.out

{ ./lab1.exe>run.out; } 2>> run_error.out 

diff z.out run.out>diff.out

valgrind --leak-check=yes ./lab1.exe 2> mem.out

#chmod go+r *.out
#chmod go+x .
ls -l



